"""empty message

Revision ID: 63968a79e624
Revises: 8f134e97c67f
Create Date: 2018-05-06 01:52:58.520301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63968a79e624'
down_revision = '8f134e97c67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.create_unique_constraint(None, 'menu', ['menu_id'])
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'user_id')
    op.drop_constraint(None, 'menu', type_='unique')
    op.create_table('orders',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], name='orders_order_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'order_id', name='orders_pkey')
    )
    # ### end Alembic commands ###
